// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skphmgkicxdsktkgqqnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrcGhtZ2tpY3hkc2t0a2dxcW5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMTYxNjEsImV4cCI6MjA2MDc5MjE2MX0.eu646I8T8nA7T7RAmyqKiGYc0Wm5Ra4lC9kP54s6byU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});